### ISSUE TITLE
Won't automatically reconnect after power up of ESP32

### ISSUE THREAD

**Issue by icooper9000** [T-vK/ESP32-BLE-Keyboard#124]
The example works fine after pairing with my PC. 
However if my ESP32 is powered down and up then it doesn't work (keyboard commands sent from ESP32 don't work). According to COM port on Arduino messages are being sent and on the PC Bluetooth panel it shows it as connected but it doesn't work until I remove the Bluetooth pairing in the PC and re pair it again,, then its ok until the next power cycle.  

My PC has Bluetooth keyboard and mouse, which don't suffer the same problem. Is there anything I need to do to the code, or am I missing something?  Cheers Ian

**Comment by icooper9000** [comment]
Hi sivar2311, thanks, that works!!  
I was running 0..3.0, I think. Anyway I deleted the library and reinstalled beta 0.3.1 and it all reconnects and functions perfectly after power cycle of the ESP32, or power cycle of the PC.  Thanks again 

How can I tell which version of the library I have?

**Comment by sivar2311** [comment]
You can check the version in the [library.properties](https://github.com/T-vK/ESP32-BLE-Keyboard/blob/4d93a0497dd307f237a83bcf69aa1ae21f496bcc/library.properties#L2) file on your harddisk.

**Comment by icooper9000** [comment]
many thanks
