### ISSUE TITLE
Hide Battery Level

### ISSUE THREAD

**Issue by Maxim0x00k** [T-vK/ESP32-BLE-Keyboard#144]
Hi everyone! Can you say how can i hide battery level on my Iphone. I know what i can change battery level with (setbatterylevel) but if i choose 0% it still show this
![photo_2022-01-27_17-09-19](https://user-images.githubusercontent.com/95305923/151375136-e368ac2f-7087-442f-ba8f-1c7029c758c4.jpg)

**Comment by Maxim0x00k** [comment]
Thanks for the answer! Can you tell which lines are responsible for showing the battery ? Because if i don't use third paramiter (BleKeyboard bleKeyboard("Bluetooth Device Name", "Bluetooth Device Manufacturer", 100);) device shows me 100%. I guess that it is necessary to make changes to the "BleKeyboard.h" or "BleKeyboard.cpp"

**Comment by T-vK** [comment]
I'd look for all lines saying something about battery.

**Comment by BG2CRW** [comment]
you can set it 101(101~255), it will hide.
