### ISSUE TITLE
German-Umlaute/Layout

### ISSUE THREAD

**Issue by lasys** [T-vK/ESP32-BLE-Keyboard#17]
Hi,
I tried to send some german "umlaute" something like ö,ä,ü but my iPad does not receive anthing.
Also the "<"-sign is displayed as ";". On my iPad I switched between the German and English keyboard layout, but it does not really help. Is it possible to switch the keyboard layout on the esp32-ble-keyboard or do you know how to solve this?

Thanks!

**Comment by T-vK** [comment]
The library assumes a US keyboard layout. Lookup a picture of a US keyboard, then you should be able to translate it. E.g. "z" and "y" are swapped.

**Comment by lasys** [comment]
Great, it works. Thank you
