### ISSUE TITLE
Can connect to android but nothing is being sent over

### ISSUE THREAD

**Issue by smokingpacman** [T-vK/ESP32-BLE-Keyboard#220]
Hey, I can get bluetooth to connect and I know it is connected because on the serial monitor, the ESP32 is trying to send over the keys, however, nothing is actually reaching the Android device. I have a text editor open and nothing is being sent across. I'm unsure why this is an issue because I tried the other ESP32 Bluetooth Keyboard library by ManuelBL and that was sending keystrokes over just fine, the only issue is I need media keys. Any idea as to what might fix this?

**Comment by vorlovsky** [comment]
This one can be fixed by passing `ESP_LE_AUTH_BOND` value to `pSecurity->setAuthenticationMode()` call in BleKeyboard.cpp file, line 125.
