### ISSUE TITLE
Example program won't compile with Arduino ESP32 board software v3.x

### ISSUE THREAD

**Issue by db123** [T-vK/ESP32-BLE-Keyboard#309]
The SendKeyStrokes example program compiles and runs correctly if I change the Arduino ESP32 board software back to version 2.0.17 in Boards Manager.
It won't compile with later versions 3.x.

**Comment by kotoar** [comment]
It's an issue of casting from `std::string` (C++ STL) to `String` (Arduino WString) for `deviceName` and `deviceManufacturer`. After adding convert for the two strings, it compiles for me. 
Also noticed the fixing PR has been created but not merged yet. https://github.com/T-vK/ESP32-BLE-Keyboard/pull/303

**Comment by db123** [comment]
Thanks for the reply.
