### ISSUE TITLE
Arduino Compile Error

### ISSUE THREAD

**Issue by hasantahsindagli** [T-vK/ESP32-BLE-Keyboard#320]
Hi,
I wrote a code to send keyboard keys to pc with buttons using ESP32. But I am getting errors during compilation. I would be glad if you could help me.

[Compilation Error.txt](https://github.com/user-attachments/files/16690420/Compilation.Error.txt)
[ESP32.ino.txt](https://github.com/user-attachments/files/16690421/ESP32.ino.txt)

**Comment by eticaretmuhendisi** [comment]
Hi @hasantahsindagli,
Esp32's core files have been modified with 3.0.0, so there is an incompatibility. The workaround is to revert to version 2.0.17 until the library developers bring an update.

https://forum.arduino.cc/t/ble-combo-failing-to-compile/1274352/2

**Comment by hasantahsindagli** [comment]
> Hi @hasantahsindagli, Esp32's core files have been modified with 3.0.0, so there is an incompatibility. The workaround is to revert to version 2.0.17 until the library developers bring an update.
> 
> https://forum.arduino.cc/t/ble-combo-failing-to-compile/1274352/2

Teşekkür ederim

**Comment by Grahack** [comment]
Thanks. For the record is there an issue here we can follow to be kept updated.

**Comment by Halphas** [comment]
tenks brov
