### ISSUE TITLE
issue on line 78 of ble characteristic file.

### ISSUE THREAD

**Issue by el-professorr** [T-vK/ESP32-BLE-Keyboard#339]
this is line 78 of the file Ble Characteristic .
  void setValue(String value);
everytime when trying to upload code, it throws an error with exit code status 1. says "no defined value" or something like that. would you please look into it?

**Comment by vtraveller** [comment]
This is a very easy fix.  For any String setValue() simply add .c_str() for the arg.

I simply edited:

```
...\Arduino\libraries\ESP32_BLE_Keyboard\BleKeyboard.cpp:106 ->
BLEDevice::init(deviceName.c_str());

...\Arduino\libraries\ESP32_BLE_Keyboard\BleKeyboard.cpp:107:
hid->manufacturer()->setValue(deviceManufacturer.c_str());
```

Everything worked fine on my Windows 11 machine.
