### ISSUE TITLE
MacOS (10.15.1 (19B88)) /System Preferences/Bluetooth device initially discovers with ID instead of the name

### ISSUE THREAD

**Issue by nikolayrantsev** [T-vK/ESP32-BLE-Keyboard#35]
When you're connecting device for the first time after uploading the code and rebooting ESP32, 
it discovers with the factory name, not defined in the code

![Bluetooth 2020-08-08 18-00-40](https://user-images.githubusercontent.com/59288233/89713747-6fb0ab80-d9a2-11ea-9f78-870a12af5481.png)

When devices paired, it shows with the defined name in the code:

`BleKeyboard bleKeyboard("Swiping");`

![Bluetooth 2020-08-08 18-15-51](https://user-images.githubusercontent.com/59288233/89713865-3fb5d800-d9a3-11ea-83ca-c78f25636956.png)

**Comment by T-vK** [comment]
I think that's a Mac "feature". If no name is specified, it would fall back to "ESP32 Bluetooth Mouse". What your Mac is showing seems to be a the Mac address with dashes instead of colons. I would assume that it shows the correct name after a while or maybe after reloading the list?

**Comment by nikolayrantsev** [comment]
Yeah, the correct name shows after turning Bluetooth on/off

**Comment by aovestdipaperino** [comment]
I realized that MacOS seems sensitive to chars.
KBV2 is ok
KBV2.0 is not ok

**Comment by aovestdipaperino** [comment]
Created a [PR](https://github.com/T-vK/ESP32-BLE-Keyboard/pull/49)

**Comment by T-vK** [comment]
Thank you, I have accepted the PR.
