### ISSUE TITLE
KEY_MEDIA_VOLUME_UP (and other media keys) don't seem to work on my Android Device

### ISSUE THREAD

**Issue by speendo** [T-vK/ESP32-BLE-Keyboard#4]
First of all, thank you very much for your work on this project.
Also, I have to apologize, that my issue might not be too insightful - I am just starting with Bluetooth...

I was able to connect my ESP32 with my Android device. However, I tried several media keys (e.g. `KEY_MEDIA_VOLUME_UP` and `KEY_MEDIA_PLAY_PAUSE` however, they have not been recognized (or at least, the Android device showed no reaction).

What could be the reason for that?

**Comment by T-vK** [comment]
What is your Android version?
Do the other keys work on your Androidi device?
Do the media keys work when you try it with a different device (e.g. a Windows or Apple device)?

**Comment by speendo** [comment]
Sorry, I didn't have the chance to test most of that, as I don't have too many bluetooth devices available atm.

I am using Android 9 and I can confirm that characters and the `Enter` key are working as expected.

**Comment by speendo** [comment]
Sorry, it seems I didn't try hard enough yesterday. Today I was able to make it work.

Sorry for the inconvenience!

**Comment by T-vK** [comment]
Neat. Do you know what caused your issue? (Just in case someone else gets the same problem in the future.)

**Comment by speendo** [comment]
Thank you for your help!

Actually, I don't know exactly, but maybe the problem was, that I issued multiple `bleKeyboard.write()` commands without `delay()` between them.

However, I cannot tell if this was the reason or if it was something else...

**Comment by speendo** [comment]
Thank you for your help!

Actually, I don't know exactly, but maybe the problem was, that I issued multiple `bleKeyboard.write()` commands without `delay()` between them.

However, I cannot tell if this was the reason or if it was something else...
