### ISSUE TITLE
(not issue) Is there anyway of combining BLEMouse and BLEKeyboard

### ISSUE THREAD

**Issue by cetrespeo** [T-vK/ESP32-BLE-Keyboard#45]
First of all many thanks for this great piece of soft.

I am trying to emulate both keyb hid and mouse with one ESP32 but they seem to share resources.

Is there anyway to manage both with just one ESP32?

Many thanks

**Comment by T-vK** [comment]
See #14

**Comment by cetrespeo** [comment]
Thanks. Apologies for not reading the whole pannel.
