### ISSUE TITLE
tell me a synonym for the "meta" key in the library? (Android 9)

### ISSUE THREAD

**Issue by Klapautsiy** [T-vK/ESP32-BLE-Keyboard#6]
pause media - KEY_MEDIA_PLAY_PAUSE
stop media - KEY_MEDIA_STOP
META - ???

https://raw.githubusercontent.com/Klapautsiy/titanium-bicycle-for-button/gh-pages/pictures/ESP32%20BLE%20key%20android%201.jpg

**Comment by T-vK** [comment]
Take a look at https://github.com/T-vK/ESP32-BLE-Keyboard/blob/master/BleKeyboard.h
It's not a MEDIA key. It's KEY_LEFT_GUI or KEY_RIGHT_GUI.

**Comment by Klapautsiy** [comment]
thanks. did not notice the elephant in the forest.
The code quoted below works correctly on Android 9 Samsung Galaxy M20
<pre>
// run AIMP
bleKeyboard.press(KEY_LEFT_GUI);
bleKeyboard.press(0x70); // p - code ASCII 
bleKeyboard.releaseAll();
</pre>

**Comment by T-vK** [comment]
Glad I could help. :)
