### ISSUE TITLE
Problem sending F13 to F24 keys.

### ISSUE THREAD

**Issue by rp1231** [T-vK/ESP32-BLE-Keyboard#81]
Hi,
I would like to report a problem sending the keys F13 to F24.
I am able to send all the keys otherwise but these keys are not going through.

I have just tested the key F13 and F6 specifically but have mentioned the 13 to 24 range as those are not the standard keys available on the keyboard.

Also posting a link to a similar problem faced by other people using the standard keyboard.h library.
https://forum.arduino.cc/index.php?topic=324554.0
In the post it is mentioned that the Arduino keyboard code falsely translates the keycodes that are sent via Keyboard.press()
It also has a few solutions implemented by people for the usb keyboard.h library.

Maybe that has something to do with this?

Thanks

**Comment by T-vK** [comment]
Your link always redirects me to the home page of https://forum.arduino.cc

**Comment by rp1231** [comment]
Strange.....
It does not do that for me.....

**Comment by rp1231** [comment]
The problem has been resolved.
I got help from Orotavia and MetalMouse from the Deej forums.

The problem was that default descriptor had cut off those last function keys in ble_keyboard.cpp lines 56 and 59.

Changing the values
from:
LOGICAL_MAXIMUM(1), 0x65 and USAGE_MAXIMUM(1),   0x65,
to:
LOGICAL_MAXIMUM(1), 0x73 and USAGE_MAXIMUM(1),   0x73,

solved the problem.

**Comment by wjcarpenter** [comment]
OP's link worked for me.

**Comment by T-vK** [comment]
Weird, I tried Firefox and Chromium - same behavior. Anyway, glad to hear the issue is resolved now. :)
I'm sure it will help other people in the future.

**Comment by rp1231** [comment]
Maybe this can be changed in the code so that others don't go through it ?

**Comment by T-vK** [comment]
Yes, we can do that if we can verify that it works on Windows, Linux, Mac OS, Android and iOS. I can test for Android and Linux.

**Comment by rp1231** [comment]
I have tested on windows

**Comment by mathklk** [comment]
The fix works and it would be great if we can get it on the master branch.

Make the changes as described above and then unpair the bluetooth device and pair again.
As mentioned in another issue, re-pairing is required (at least on Windows)
