### ISSUE TITLE
odd issue with Notepad++

### ISSUE THREAD

**Issue by roblatour** [T-vK/ESP32-BLE-Keyboard#92]
I'm leaving this issue here.  

However, I'm not sure if it is yours or Notepad++'s to deal with.

The following two commands:
  bleKeyboard.write(KEY_RETURN);
  bleKeyboard.write("/n");

work reliably when keying into Word, WordPad, the Arduino IDE, and even this webform.  
However, neither work reliably when keying into Notepad++.

When keying into Notepad++ the commands work fine when open in a new text file, and the cursor is on the first line as long as there is no enter pressed for the end of that line already - otherwise the carriage return is often (but not always) ignored.  

for example:
`bleKeyboard.write("Hello/nThere")`
results in:

Hello
There

in Word, WordPad, the Arduino IDE, and in Notepad++ on line 1 as described above.

However, if the cursor is in a middle of Notepad++ file, what is typed out is:
HelloThere

This actually cost me about a day of debugging, as I was having my text keyed thru the bleKeyboard into a scratch document opened by Notepad++ and it took me some time to understand the issue was with where the text was being keyed to more than anything else.

So, again, not necessarily an issue for you - but it could be?  

However, definitely an awareness item for others.

Comments welcome.

**Comment by T-vK** [comment]
Some applications need delays between each keypress. Some even need delays between each press and release.
